/**
 * Educational Sections — Section Types and Generation
 *
 * Defines and generates educational response sections.
 * Sections are deterministic — extracted from content, not generated by LLM.
 */

// ============================================================================
// SECTION TYPES
// ============================================================================

export const CANONICAL_SECTION_TYPES = [
  'explanation',
  'key-concepts',
  'important-observations',
  'examples',
  'mathematical-insight',
  'engineering-perspective',
  'applications',
  'research-notes',
  'visual-suggestions',
  'laboratory-suggestions',
  'assessment-suggestions',
  'common-misconceptions',
  'related-concepts',
  'learning-path-recommendations',
  'summary',
  'next-steps',
  'references',
  'confidence'
] as const;

export type SectionType = (typeof CANONICAL_SECTION_TYPES)[number];

export interface EducationalSection {
  readonly id: string;
  readonly type: SectionType;
  readonly title: string;
  readonly content: string;
  readonly priority: number;
  readonly expandable: boolean;
  readonly defaultExpanded: boolean;
}

// ============================================================================
// SECTION GENERATION
// ============================================================================

export function generateSections(
  content: string,
  type: string,
  context: {
    mode: string;
    style: string;
    hasMathContent: boolean;
    hasCodeContent: boolean;
    hasResearchContent: boolean;
    hasVisualContent: boolean;
    hasLabContent: boolean;
    hasAssessmentContent: boolean;
  }
): readonly EducationalSection[] {
  const sections: EducationalSection[] = [];

  // Always include explanation
  sections.push(createSection('explanation', 'Explanation', content, 1, true, true));

  // Extract key concepts
  const concepts = extractKeyConcepts(content);
  if (concepts.length > 0) {
    sections.push(createSection('key-concepts', 'Key Concepts', concepts.join('\n'), 2, true, false));
  }

  // Extract examples
  const examples = extractExamples(content);
  if (examples.length > 0) {
    sections.push(createSection('examples', 'Examples', examples.join('\n\n'), 3, true, false));
  }

  // Mathematical insight
  if (context.hasMathContent || context.mode === 'advanced') {
    const mathInsight = extractMathematicalInsight(content);
    if (mathInsight) {
      sections.push(createSection('mathematical-insight', 'Mathematical Insight', mathInsight, 4, true, false));
    }
  }

  // Engineering perspective
  if (context.hasCodeContent || context.mode === 'engineering') {
    const engPerspective = extractEngineeringPerspective(content);
    if (engPerspective) {
      sections.push(createSection('engineering-perspective', 'Engineering Perspective', engPerspective, 5, true, false));
    }
  }

  // Applications
  const applications = extractApplications(content);
  if (applications.length > 0) {
    sections.push(createSection('applications', 'Applications', applications.join('\n'), 6, true, false));
  }

  // Research notes
  if (context.hasResearchContent || context.mode === 'research') {
    const researchNotes = extractResearchNotes(content);
    if (researchNotes) {
      sections.push(createSection('research-notes', 'Research Notes', researchNotes, 7, true, false));
    }
  }

  // Visual suggestions
  if (context.hasVisualContent || context.style === 'visual') {
    sections.push(createSection('visual-suggestions', 'Visual Suggestions', 'Consider creating a diagram to visualize this concept.', 8, true, false));
  }

  // Laboratory suggestions
  if (context.hasLabContent || context.mode === 'practice') {
    sections.push(createSection('laboratory-suggestions', 'Laboratory Suggestions', 'Try implementing this concept in a hands-on exercise.', 9, true, false));
  }

  // Assessment suggestions
  if (context.hasAssessmentContent) {
    sections.push(createSection('assessment-suggestions', 'Assessment Suggestions', 'Test your understanding with practice questions.', 10, true, false));
  }

  // Common misconceptions
  const misconceptions = extractMisconceptions(content);
  if (misconceptions.length > 0) {
    sections.push(createSection('common-misconceptions', 'Common Misconceptions', misconceptions.join('\n'), 11, true, false));
  }

  // Related concepts
  const related = extractRelatedConcepts(content);
  if (related.length > 0) {
    sections.push(createSection('related-concepts', 'Related Concepts', related.join(', '), 12, true, false));
  }

  // Summary
  const summary = extractSummary(content);
  if (summary) {
    sections.push(createSection('summary', 'Summary', summary, 13, true, true));
  }

  // Next steps
  const nextSteps = extractNextSteps(content);
  if (nextSteps.length > 0) {
    sections.push(createSection('next-steps', 'Next Steps', nextSteps.join('\n'), 14, true, false));
  }

  return sections;
}

// ============================================================================
// SECTION FACTORY
// ============================================================================

let sectionCounter = 0;

function createSection(
  type: SectionType,
  title: string,
  content: string,
  priority: number,
  expandable: boolean,
  defaultExpanded: boolean
): EducationalSection {
  sectionCounter++;
  return {
    id: `section-${Date.now()}-${sectionCounter}`,
    type,
    title,
    content,
    priority,
    expandable,
    defaultExpanded
  };
}

// ============================================================================
// CONTENT EXTRACTION (Deterministic)
// ============================================================================

function extractKeyConcepts(content: string): readonly string[] {
  const concepts: string[] = [];
  const lines = content.split('\n');

  for (const line of lines) {
    // Look for bold terms ( **term** )
    const boldMatches = line.match(/\*\*(.*?)\*\*/g);
    if (boldMatches) {
      for (const match of boldMatches) {
        const term = match.replace(/\*\*/g, '').trim();
        if (term.length > 2 && term.length < 50 && !concepts.includes(term)) {
          concepts.push(term);
        }
      }
    }

    // Look for definitions (term is/means/refers to)
    const defMatch = line.match(/([A-Z][a-z]+(?:\s+[a-z]+)*)\s+(?:is|are|means?|refers? to)/i);
    if (defMatch && defMatch[1]) {
      const term = defMatch[1].trim();
      if (term.length > 2 && !concepts.includes(term)) {
        concepts.push(term);
      }
    }
  }

  return concepts.slice(0, 10);
}

function extractExamples(content: string): readonly string[] {
  const examples: string[] = [];
  const lines = content.split('\n');

  for (const line of lines) {
    if (line.match(/^(for example|such as|e\.g\.|like|including)/i)) {
      examples.push(line.trim());
    }
    if (line.match(/^-\s/)) {
      examples.push(line.trim());
    }
  }

  return examples.slice(0, 5);
}

function extractMathematicalInsight(content: string): string | null {
  const mathPatterns = [
    /\$.*?\$/g,
    /\b(equation|formula|theorem|proof|derivative|integral|matrix|vector)\b/i,
    /\b(=|≤|≥|∑|∫|∂|∇)\b/
  ];

  for (const pattern of mathPatterns) {
    if (pattern.test(content)) {
      // Extract surrounding context
      const match = content.match(/.{0,100}(?:equation|formula|theorem|proof|derivative|integral|matrix|vector).{0,100}/i);
      if (match) {
        return match[0].trim();
      }
    }
  }

  return null;
}

function extractEngineeringPerspective(content: string): string | null {
  const engPatterns = [
    /\b(implement|code|algorithm|performance|optimize|scale|deploy|debug)\b/i,
    /\b(API|SDK|framework|library|runtime|compiler)\b/,
    /```[\s\S]*?```/
  ];

  for (const pattern of engPatterns) {
    if (pattern.test(content)) {
      const match = content.match(/.{0,100}(?:implement|code|algorithm|performance|optimize|scale|deploy|debug).{0,100}/i);
      if (match) {
        return match[0].trim();
      }
    }
  }

  return null;
}

function extractApplications(content: string): readonly string[] {
  const applications: string[] = [];
  const appPatterns = [
    /\b(used in|applied to|real-world|production|industry|commercial)\b/i,
    /\b(healthcare|finance|education|manufacturing|transportation)\b/i
  ];

  for (const pattern of appPatterns) {
    const matches = content.match(new RegExp(`.{0,50}${pattern.source}.{0,50}`, 'gi'));
    if (matches) {
      for (const match of matches.slice(0, 3)) {
        const cleaned = match.trim();
        if (!applications.includes(cleaned)) {
          applications.push(cleaned);
        }
      }
    }
  }

  return applications.slice(0, 5);
}

function extractResearchNotes(content: string): string | null {
  const researchPatterns = [
    /\b(study|research|paper|journal|publication|finding|evidence)\b/i,
    /\b(20[0-2]\d)\b/
  ];

  for (const pattern of researchPatterns) {
    if (pattern.test(content)) {
      const match = content.match(/.{0,100}(?:study|research|paper|journal|publication|finding|evidence).{0,100}/i);
      if (match) {
        return match[0].trim();
      }
    }
  }

  return null;
}

function extractMisconceptions(content: string): readonly string[] {
  const misconceptions: string[] = [];
  const misconPatterns = [
    /\b(common misconception|misunderstanding|often confused|not the same|actually|in fact)\b/i,
    /\b(it's not|this is wrong|incorrectly|confused with)\b/i
  ];

  for (const pattern of misconPatterns) {
    const matches = content.match(new RegExp(`.{0,50}${pattern.source}.{0,50}`, 'gi'));
    if (matches) {
      for (const match of matches.slice(0, 3)) {
        misconceptions.push(match.trim());
      }
    }
  }

  return misconceptions.slice(0, 3);
}

function extractRelatedConcepts(content: string): readonly string[] {
  const related: string[] = [];
  const relatedPatterns = [
    /\b(related to|connected to|similar to|related concepts?|also see)\b/i,
    /\b(compare with|contrast with|versus|vs\.?)\b/i
  ];

  for (const pattern of relatedPatterns) {
    const matches = content.match(new RegExp(`.{0,30}${pattern.source}.{0,30}`, 'gi'));
    if (matches) {
      for (const match of matches.slice(0, 3)) {
        const cleaned = match.trim();
        if (!related.includes(cleaned)) {
          related.push(cleaned);
        }
      }
    }
  }

  return related.slice(0, 5);
}

function extractSummary(content: string): string | null {
  // Take first 2 sentences as summary
  const sentences = content.split(/[.!?]+/).filter(s => s.trim().length > 10);
  if (sentences.length >= 2) {
    return `${sentences[0].trim()}. ${sentences[1].trim()}.`;
  }
  return sentences.length > 0 ? sentences[0].trim() + '.' : null;
}

function extractNextSteps(content: string): readonly string[] {
  const steps: string[] = [];
  const stepPatterns = [
    /\b(next step|further reading|explore|learn more|try|practice)\b/i,
    /\b(go to|navigate to|open|continue with)\b/i
  ];

  for (const pattern of stepPatterns) {
    const matches = content.match(new RegExp(`.{0,30}${pattern.source}.{0,30}`, 'gi'));
    if (matches) {
      for (const match of matches.slice(0, 2)) {
        steps.push(match.trim());
      }
    }
  }

  return steps.slice(0, 3);
}

// ============================================================================
// UTILITIES
// ============================================================================

function estimateReadingTime(content: string): number {
  const wordsPerMinute = 200;
  const words = content.split(/\s+/).length;
  return Math.ceil(words / wordsPerMinute);
}
