/**
 * Educational Actions — Action Types and Generation
 *
 * Defines suggested actions for the response.
 * Actions are deterministic — extracted from context, not generated by LLM.
 */

// ============================================================================
// ACTION TYPES
// ============================================================================

export const CANONICAL_ACTION_TYPES = [
  'explain-more',
  'show-diagram',
  'generate-quiz',
  'open-laboratory',
  'compare-concepts',
  'show-applications',
  'view-references',
  'practice',
  'save',
  'continue-learning',
  'simplify',
  'deepen',
  'show-examples',
  'generate-flashcards',
  'view-visual'
] as const;

export type ActionType = (typeof CANONICAL_ACTION_TYPES)[number];

export interface EducationalAction {
  readonly id: string;
  readonly type: ActionType;
  readonly label: string;
  readonly description: string;
  readonly icon: string;
  readonly priority: number;
  readonly enabled: boolean;
}

// ============================================================================
// ACTION GENERATION
// ============================================================================

export function generateActions(
  content: string,
  responseType: string,
  context: {
    mode: string;
    style: string;
    hasMathContent: boolean;
    hasCodeContent: boolean;
    hasLabContent: boolean;
    hasAssessmentContent: boolean;
  }
): readonly EducationalAction[] {
  const actions: EducationalAction[] = [];

  // Always available actions
  actions.push(createAction('explain-more', 'Explain More', 'Get a more detailed explanation', '\u{1F50D}', 1, true));
  actions.push(createAction('simplify', 'Simplify', 'Get a simpler explanation', '\u{1F4DD}', 2, true));

  // Context-dependent actions
  if (context.hasMathContent) {
    actions.push(createAction('deepen', 'Deepen', 'Get a more technical explanation', '\u{1F4D6}', 3, true));
  }

  if (context.hasCodeContent || context.mode === 'engineering') {
    actions.push(createAction('show-diagram', 'Show Diagram', 'View a visual representation', '\u{1F4CA}', 4, true));
    actions.push(createAction('practice', 'Practice', 'Try implementing this concept', '\u{1F9EA}', 5, true));
  }

  if (context.hasLabContent || context.mode === 'practice') {
    actions.push(createAction('open-laboratory', 'Open Laboratory', 'Start a hands-on exercise', '\u{1F52C}', 6, true));
  }

  if (context.hasAssessmentContent) {
    actions.push(createAction('generate-quiz', 'Generate Quiz', 'Test your understanding', '\u{2705}', 7, true));
    actions.push(createAction('generate-flashcards', 'Generate Flashcards', 'Create study flashcards', '\u{1F4CF}', 8, true));
  }

  // Comparison action
  if (content.includes(' vs ') || content.includes(' versus ') || responseTypeDefines(responseType, 'comparison')) {
    actions.push(createAction('compare-concepts', 'Compare Concepts', 'See how this relates to other concepts', '\u{2194}\uFE0F', 9, true));
  }

  // Applications
  if (content.includes('used in') || content.includes('applied') || responseTypeDefines(responseType, 'application')) {
    actions.push(createAction('show-applications', 'Show Applications', 'View real-world applications', '\u{1F3ED}', 10, true));
  }

  // References
  if (content.includes('study') || content.includes('research') || content.includes('paper')) {
    actions.push(createAction('view-references', 'View References', 'See supporting research', '\u{1F4DA}', 11, true));
  }

  // Visual
  if (context.style === 'visual' || content.includes('visualize') || content.includes('diagram')) {
    actions.push(createAction('view-visual', 'View Visual', 'See visual representation', '\u{1F3A8}', 12, true));
  }

  // Examples
  if (content.includes('example') || content.includes('for instance')) {
    actions.push(createAction('show-examples', 'Show Examples', 'View more examples', '\u{1F4CB}', 13, true));
  }

  // Save and continue
  actions.push(createAction('save', 'Save', 'Save this response', '\u{1F4BE}', 14, true));
  actions.push(createAction('continue-learning', 'Continue Learning', 'Explore related topics', '\u{27A1}\uFE0F', 15, true));

  return actions;
}

// ============================================================================
// ACTION FACTORY
// ============================================================================

let actionCounter = 0;

function createAction(
  type: ActionType,
  label: string,
  description: string,
  icon: string,
  priority: number,
  enabled: boolean
): EducationalAction {
  actionCounter++;
  return {
    id: `action-${Date.now()}-${actionCounter}`,
    type,
    label,
    description,
    icon,
    priority,
    enabled
  };
}

// ============================================================================
// UTILITIES
// ============================================================================

function responseTypeDefines(responseType: string, type: string): boolean {
  return responseType === type;
}

export function getActionByType(
  actions: readonly EducationalAction[],
  type: ActionType
): EducationalAction | undefined {
  return actions.find(a => a.type === type);
}

export function getEnabledActions(
  actions: readonly EducationalAction[]
): readonly EducationalAction[] {
  return actions.filter(a => a.enabled);
}

export function getActionsByPriority(
  actions: readonly EducationalAction[]
): readonly EducationalAction[] {
  return [...actions].sort((a, b) => a.priority - b.priority);
}
