/**
 * Educational Cards — Card Types and Generation
 *
 * Defines rich educational cards for the response.
 * Cards are deterministic — extracted from content, not generated by LLM.
 */

// ============================================================================
// CARD TYPES
// ============================================================================

export const CANONICAL_CARD_TYPES = [
  'concept',
  'comparison',
  'timeline',
  'warning',
  'misconception',
  'research',
  'application',
  'laboratory',
  'assessment',
  'reference',
  'visual',
  'code',
  'formula',
  'step-by-step'
] as const;

export type CardType = (typeof CANONICAL_CARD_TYPES)[number];

export interface EducationalCard {
  readonly id: string;
  readonly type: CardType;
  readonly title: string;
  readonly content: string;
  readonly metadata: CardMetadata;
  readonly expandable: boolean;
}

export interface CardMetadata {
  readonly priority: number;
  readonly category: string;
  readonly tags: readonly string[];
  readonly relatedConcepts: readonly string[];
}

// ============================================================================
// CARD GENERATION
// ============================================================================

export function generateCards(
  content: string,
  sections: readonly { type: string; content: string }[],
  context: {
    mode: string;
    style: string;
    hasMathContent: boolean;
    hasCodeContent: boolean;
    hasResearchContent: boolean;
  }
): readonly EducationalCard[] {
  const cards: EducationalCard[] = [];

  // Concept card for key definitions
  const concepts = extractConceptsForCards(content);
  for (const concept of concepts) {
    cards.push(createCard('concept', concept.title, concept.definition, {
      priority: 1,
      category: 'definition',
      tags: ['concept', 'definition'],
      relatedConcepts: []
    }));
  }

  // Comparison cards
  if (content.includes(' vs ') || content.includes(' versus ') || content.includes(' compared to ')) {
    const comparison = extractComparison(content);
    if (comparison) {
      cards.push(createCard('comparison', 'Comparison', comparison, {
        priority: 2,
        category: 'analysis',
        tags: ['comparison', 'analysis'],
        relatedConcepts: []
      }));
    }
  }

  // Code card
  if (context.hasCodeContent) {
    const codeBlock = extractCodeBlock(content);
    if (codeBlock) {
      cards.push(createCard('code', 'Code Example', codeBlock, {
        priority: 3,
        category: 'implementation',
        tags: ['code', 'example'],
        relatedConcepts: []
      }));
    }
  }

  // Formula card
  if (context.hasMathContent) {
    const formula = extractFormula(content);
    if (formula) {
      cards.push(createCard('formula', 'Formula', formula, {
        priority: 3,
        category: 'mathematics',
        tags: ['formula', 'math'],
        relatedConcepts: []
      }));
    }
  }

  // Step-by-step card
  const steps = extractSteps(content);
  if (steps.length > 0) {
    cards.push(createCard('step-by-step', 'Step-by-Step', steps.join('\n'), {
      priority: 4,
      category: 'process',
      tags: ['steps', 'process'],
      relatedConcepts: []
    }));
  }

  // Warning card for caveats
  const warnings = extractWarnings(content);
  if (warnings.length > 0) {
    cards.push(createCard('warning', 'Important Notes', warnings.join('\n'), {
      priority: 5,
      category: 'caution',
      tags: ['warning', 'important'],
      relatedConcepts: []
    }));
  }

  // Misconception card
  const misconceptions = extractMisconceptionsForCards(content);
  if (misconceptions.length > 0) {
    cards.push(createCard('misconception', 'Common Misconceptions', misconceptions.join('\n'), {
      priority: 6,
      category: 'correction',
      tags: ['misconception', 'correction'],
      relatedConcepts: []
    }));
  }

  // Research card
  if (context.hasResearchContent) {
    const researchInfo = extractResearchInfo(content);
    if (researchInfo) {
      cards.push(createCard('research', 'Research Context', researchInfo, {
        priority: 7,
        category: 'research',
        tags: ['research', 'evidence'],
        relatedConcepts: []
      }));
    }
  }

  // Application card
  const applications = extractApplicationsForCards(content);
  if (applications.length > 0) {
    cards.push(createCard('application', 'Real-World Applications', applications.join('\n'), {
      priority: 8,
      category: 'application',
      tags: ['application', 'real-world'],
      relatedConcepts: []
    }));
  }

  // Visual card
  const visualSuggestions = extractVisualSuggestions(content);
  if (visualSuggestions.length > 0) {
    cards.push(createCard('visual', 'Visual Representation', visualSuggestions.join('\n'), {
      priority: 9,
      category: 'visual',
      tags: ['visual', 'diagram'],
      relatedConcepts: []
    }));
  }

  return cards;
}

// ============================================================================
// CARD FACTORY
// ============================================================================

let cardCounter = 0;

function createCard(
  type: CardType,
  title: string,
  content: string,
  metadata: CardMetadata
): EducationalCard {
  cardCounter++;
  return {
    id: `card-${Date.now()}-${cardCounter}`,
    type,
    title,
    content,
    metadata,
    expandable: content.length > 200
  };
}

// ============================================================================
// CONTENT EXTRACTION FOR CARDS
// ============================================================================

function extractConceptsForCards(content: string): readonly { title: string; definition: string }[] {
  const concepts: { title: string; definition: string }[] = [];
  const lines = content.split('\n');

  for (const line of lines) {
    const match = line.match(/\*\*(.*?)\*\*\s*(?:is|are|means?|refers? to)\s*(.*?)(?:\.|$)/i);
    if (match && match[1] && match[2]) {
      concepts.push({
        title: match[1].trim(),
        definition: match[2].trim()
      });
    }
  }

  return concepts.slice(0, 3);
}

function extractComparison(content: string): string | null {
  const match = content.match(/(.*?(?: vs | versus | compared to ).*?)(?:\.|$)/i);
  return match ? match[1].trim() : null;
}

function extractCodeBlock(content: string): string | null {
  const match = content.match(/```[\s\S]*?```/);
  return match ? match[0].replace(/```\w*\n?/g, '').trim() : null;
}

function extractFormula(content: string): string | null {
  const match = content.match(/\$.*?\$/);
  return match ? match[0].trim() : null;
}

function extractSteps(content: string): readonly string[] {
  const steps: string[] = [];
  const lines = content.split('\n');

  for (const line of lines) {
    const match = line.match(/^(\d+[\.\)]\s*.+)/);
    if (match) {
      steps.push(match[1].trim());
    }
  }

  return steps.slice(0, 10);
}

function extractWarnings(content: string): readonly string[] {
  const warnings: string[] = [];
  const warnPatterns = [
    /\b(warning|caution|note|important|be careful|watch out)\b/i,
    /\b(don't|do not|never|avoid|prevent)\b/i
  ];

  for (const pattern of warnPatterns) {
    const matches = content.match(new RegExp(`.{0,30}${pattern.source}.{0,50}`, 'gi'));
    if (matches) {
      for (const match of matches.slice(0, 2)) {
        warnings.push(match.trim());
      }
    }
  }

  return warnings.slice(0, 3);
}

function extractMisconceptionsForCards(content: string): readonly string[] {
  const misconceptions: string[] = [];
  const patterns = [
    /\b(misconception|misunderstanding|common error|incorrectly|not the same)\b/i,
    /\b(it's not|this is wrong|actually|in fact|contrary to)\b/i
  ];

  for (const pattern of patterns) {
    const matches = content.match(new RegExp(`.{0,30}${pattern.source}.{0,50}`, 'gi'));
    if (matches) {
      for (const match of matches.slice(0, 2)) {
        misconceptions.push(match.trim());
      }
    }
  }

  return misconceptions.slice(0, 3);
}

function extractResearchInfo(content: string): string | null {
  const match = content.match(/.{0,100}(?:study|research|paper|journal|finding|evidence).{0,100}/i);
  return match ? match[0].trim() : null;
}

function extractApplicationsForCards(content: string): readonly string[] {
  const applications: string[] = [];
  const patterns = [
    /\b(used in|applied to|real-world|production|industry)\b/i,
    /\b(healthcare|finance|education|manufacturing|transportation)\b/i
  ];

  for (const pattern of patterns) {
    const matches = content.match(new RegExp(`.{0,30}${pattern.source}.{0,30}`, 'gi'));
    if (matches) {
      for (const match of matches.slice(0, 2)) {
        applications.push(match.trim());
      }
    }
  }

  return applications.slice(0, 3);
}

function extractVisualSuggestions(content: string): readonly string[] {
  const suggestions: string[] = [];
  const patterns = [
    /\b(diagram|flowchart|graph|chart|visualization|illustration)\b/i,
    /\b(visualize|imagine|picture|depict|represent)\b/i
  ];

  for (const pattern of patterns) {
    const matches = content.match(new RegExp(`.{0,20}${pattern.source}.{0,30}`, 'gi'));
    if (matches) {
      for (const match of matches.slice(0, 2)) {
        suggestions.push(match.trim());
      }
    }
  }

  return suggestions.slice(0, 3);
}
