/**
 * Conversation Summary — Deterministic Summary Generation
 *
 * Generates rolling summaries from conversation messages.
 * Summary is deterministic — extracted from messages, not generated by LLM.
 */

import type { ConversationMessage } from './ConversationMessage.ts';
import type { ConversationSession } from './ConversationSession.ts';
import { updateSessionSummary } from './ConversationSession.ts';

// ============================================================================
// SUMMARY GENERATION
// ============================================================================

export function generateSummary(session: ConversationSession): string {
  const messages = session.messages;
  if (messages.length === 0) return '';

  const parts: string[] = [];

  // Extract conversation topic from first user message
  const firstUserMsg = messages.find(m => m.type === 'user');
  if (firstUserMsg) {
    parts.push(`Topic: ${firstUserMsg.content.substring(0, 100)}`);
  }

  // Count messages by type
  const userCount = messages.filter(m => m.type === 'user').length;
  const assistantCount = messages.filter(m => m.type === 'assistant').length;

  parts.push(`Discussion: ${userCount} questions, ${assistantCount} responses`);

  // Extract key artifacts
  const artifacts = messages
    .filter(m => m.artifacts && m.artifacts.length > 0)
    .flatMap(m => m.artifacts || []);

  if (artifacts.length > 0) {
    const artifactTypes = [...new Set(artifacts.map(a => a.type))];
    parts.push(`Created: ${artifactTypes.join(', ')}`);
  }

  // Extract context if available
  const contextMsg = messages.find(m => m.type === 'context');
  if (contextMsg) {
    parts.push(`Context: ${contextMsg.content.substring(0, 80)}`);
  }

  // Duration
  if (messages.length >= 2) {
    const first = new Date(messages[0].timestamp).getTime();
    const last = new Date(messages[messages.length - 1].timestamp).getTime();
    const durationMs = last - first;
    const durationMin = Math.round(durationMs / 60000);
    if (durationMin > 0) {
      parts.push(`Duration: ${durationMin} min`);
    }
  }

  return parts.join(' | ');
}

export function updateConversationSummary(
  session: ConversationSession
): ConversationSession {
  const summary = generateSummary(session);
  return updateSessionSummary(session, summary);
}

// ============================================================================
// SUMMARY QUERIES
// ============================================================================

export function getSummarySize(session: ConversationSession): number {
  return session.summary.length;
}

export function hasSummary(session: ConversationSession): boolean {
  return session.summary.length > 0;
}

export function getSummaryExcerpt(
  session: ConversationSession,
  maxLength: number = 100
): string {
  if (session.summary.length <= maxLength) {
    return session.summary;
  }
  return session.summary.substring(0, maxLength) + '...';
}

// ============================================================================
// SUMMARY COMPARISON
// ============================================================================

export function compareSummaries(
  summary1: string,
  summary2: string
): boolean {
  return summary1 === summary2;
}

export function isSummaryStale(
  session: ConversationSession,
  messageThreshold: number = 5
): boolean {
  const lastSummaryUpdate = session.metadata.summarySize;
  const currentMessages = session.messages.length;

  // Summary is stale if many messages since last update
  return currentMessages - (lastSummaryUpdate / 10) > messageThreshold;
}
