from enum import StrEnum


class FixtureClassification(StrEnum):
    TEST_FIXTURE = "TEST_FIXTURE"


class FixtureCanonicality(StrEnum):
    NON_CANONICAL = "NON_CANONICAL"


class FixtureSharedContractStatus(StrEnum):
    NOT_A_FINAL_SHARED_CONTRACT = "NOT_A_FINAL_SHARED_CONTRACT"


class FixtureValidationStatus(StrEnum):
    STRUCTURALLY_VALID = "STRUCTURALLY_VALID"
    STRUCTURALLY_REJECTED = "STRUCTURALLY_REJECTED"


class IdempotencyStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"


class IdempotencyResponseReferenceType(StrEnum):
    FIXTURE_RECORD = "FIXTURE_RECORD"


class AuditEventType(StrEnum):
    FIXTURE_INGESTION_ACCEPTED = "FIXTURE_INGESTION_ACCEPTED"
    FIXTURE_INGESTION_REJECTED = "FIXTURE_INGESTION_REJECTED"
    IDEMPOTENCY_REPLAYED = "IDEMPOTENCY_REPLAYED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    FIXTURE_SUPERSEDED = "FIXTURE_SUPERSEDED"


class AuditActorType(StrEnum):
    SYSTEM_FIXTURE_ADAPTER = "SYSTEM_FIXTURE_ADAPTER"
    SYSTEM_IDEMPOTENCY = "SYSTEM_IDEMPOTENCY"


class AuditSubjectType(StrEnum):
    FIXTURE_RECORD = "FIXTURE_RECORD"
    IDEMPOTENCY_RECORD = "IDEMPOTENCY_RECORD"


class AuditOutcome(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    REPLAYED = "REPLAYED"
    CONFLICT = "CONFLICT"
    SUPERSEDED = "SUPERSEDED"
