/**
 * NV-2000-D8-OPT-14 — Deterministic Assessment Evidence & Governance Layer Kernel
 *
 * Pure deterministic compose functions for assessment evidence governance.
 * The Assessment Agent models evidence metadata that describes educational
 * evidence generated by assessments. It stores evidence provenance, validates
 * evidence structures, governs evidence lifecycle, and maintains audit metadata.
 * It never evaluates learners, computes mastery, assigns grades, infers
 * competency, or performs evidence analysis.
 *
 * Guarantees:
 * - Same inputs always produce identical outputs.
 * - No global mutable state reads.
 * - No random values.
 * - No time dependency.
 * - Canonical order is always preserved.
 *
 * Deterministic. No Math.random. No Date.now.
 */

import {
  type AssessmentArtifactWithEvidence,
  type AssessmentEvidence,
  type AssessmentEvidenceProvenance,
  type AssessmentEvidenceTrace,
  type AssessmentGovernanceLevel,
  type EvidenceAuditMetadata,
  type EvidenceConfidenceLevel,
  type EvidenceGovernance,
  type EvidenceGovernanceLevel,
  type EvidenceInput,
  type EvidenceReference,
  type EvidenceRegistry,
  type EvidenceRegistryMetadata,
  type EvidenceRelationship,
  type EvidenceSource,
  type EvidenceStatus,
  type EvidenceTraceType,
  type EvidenceType,
  CANONICAL_ASSESSMENT_GOVERNANCE,
  CANONICAL_EVIDENCE_CONFIDENCE_LEVELS,
  CANONICAL_EVIDENCE_GOVERNANCE_LEVELS,
  CANONICAL_EVIDENCE_SOURCES,
  CANONICAL_EVIDENCE_STATUS,
  CANONICAL_EVIDENCE_TRACE_TYPES,
  CANONICAL_EVIDENCE_TYPES,
} from './AssessmentAgentContract.ts';

// ============================================================================
// HELPER FUNCTIONS — Canonical lookups and type guards
// ============================================================================

/**
 * Type guard: is the value a supported evidence type?
 */
export function isSupportedEvidenceType(
  value: string,
): value is EvidenceType {
  return CANONICAL_EVIDENCE_TYPES.includes(
    value as EvidenceType,
  );
}

/**
 * Type guard: is the value a supported evidence source?
 */
export function isSupportedEvidenceSource(
  value: string,
): value is EvidenceSource {
  return CANONICAL_EVIDENCE_SOURCES.includes(
    value as EvidenceSource,
  );
}

/**
 * Type guard: is the value a supported evidence confidence level?
 */
export function isSupportedEvidenceConfidenceLevel(
  value: string,
): value is EvidenceConfidenceLevel {
  return CANONICAL_EVIDENCE_CONFIDENCE_LEVELS.includes(
    value as EvidenceConfidenceLevel,
  );
}

/**
 * Type guard: is the value a supported evidence governance level?
 */
export function isSupportedEvidenceGovernanceLevel(
  value: string,
): value is EvidenceGovernanceLevel {
  return CANONICAL_EVIDENCE_GOVERNANCE_LEVELS.includes(
    value as EvidenceGovernanceLevel,
  );
}

/**
 * Type guard: is the value a supported evidence trace type?
 */
export function isSupportedEvidenceTraceType(
  value: string,
): value is EvidenceTraceType {
  return CANONICAL_EVIDENCE_TRACE_TYPES.includes(
    value as EvidenceTraceType,
  );
}

/**
 * Type guard: is the value a supported evidence status?
 */
export function isSupportedEvidenceStatus(
  value: string,
): value is EvidenceStatus {
  return CANONICAL_EVIDENCE_STATUS.includes(
    value as EvidenceStatus,
  );
}

/**
 * Type guard: is the value a supported evidence governance level?
 */
export function isSupportedEvidenceGovernance(
  value: string,
): value is AssessmentGovernanceLevel {
  return CANONICAL_ASSESSMENT_GOVERNANCE.includes(
    value as AssessmentGovernanceLevel,
  );
}

/**
 * Returns a copy of canonical evidence types.
 */
export function getCanonicalEvidenceTypes(): readonly EvidenceType[] {
  return [...CANONICAL_EVIDENCE_TYPES];
}

/**
 * Returns a copy of canonical evidence sources.
 */
export function getCanonicalEvidenceSources(): readonly EvidenceSource[] {
  return [...CANONICAL_EVIDENCE_SOURCES];
}

/**
 * Returns a copy of canonical evidence confidence levels.
 */
export function getCanonicalEvidenceConfidenceLevels(): readonly EvidenceConfidenceLevel[] {
  return [...CANONICAL_EVIDENCE_CONFIDENCE_LEVELS];
}

/**
 * Returns a copy of canonical evidence governance levels.
 */
export function getCanonicalEvidenceGovernanceLevels(): readonly EvidenceGovernanceLevel[] {
  return [...CANONICAL_EVIDENCE_GOVERNANCE_LEVELS];
}

/**
 * Returns a copy of canonical evidence trace types.
 */
export function getCanonicalEvidenceTraceTypes(): readonly EvidenceTraceType[] {
  return [...CANONICAL_EVIDENCE_TRACE_TYPES];
}

/**
 * Returns a copy of canonical evidence statuses.
 */
export function getCanonicalEvidenceStatuses(): readonly EvidenceStatus[] {
  return [...CANONICAL_EVIDENCE_STATUS];
}

// ============================================================================
// COMPOSE FUNCTIONS — Pure deterministic composition
// ============================================================================

/**
 * Deterministic ID generator.
 */
function _deterministicId(prefix: string, parts: readonly string[]): string {
  const slug = parts
    .join('-')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 60);
  return `${prefix}-${slug}`;
}

/**
 * Compose an immutable AssessmentEvidenceProvenance.
 */
export function composeAssessmentEvidenceProvenance(params: {
  readonly provider: string;
  readonly source: string;
  readonly reviewStatus: EvidenceStatus;
  readonly reviewDate: string;
  readonly version: string;
  readonly rationale: string;
}): AssessmentEvidenceProvenance {
  return {
    provider: params.provider,
    source: params.source,
    reviewStatus: params.reviewStatus,
    reviewDate: params.reviewDate,
    version: params.version,
    rationale: params.rationale,
  };
}

/**
 * Compose an immutable AssessmentEvidenceTrace.
 */
export function composeAssessmentEvidenceTrace(params: {
  readonly traceId: string;
}): AssessmentEvidenceTrace {
  return {
    traceId: params.traceId,
    deterministic: true,
    generatedFrom: 'deterministic_evidence_kernel',
    randomUsed: false,
    timeDependency: false,
  };
}

/**
 * Compose an immutable EvidenceReference.
 */
export function composeEvidenceReference(params: {
  readonly id: string;
  readonly evidenceType: EvidenceType;
  readonly source: EvidenceSource;
  readonly description: string;
}): EvidenceReference {
  return {
    id: params.id,
    evidenceType: params.evidenceType,
    source: params.source,
    description: params.description,
  };
}

/**
 * Compose an immutable EvidenceRelationship.
 */
export function composeEvidenceRelationship(params: {
  readonly id: string;
  readonly sourceEvidenceId: string;
  readonly targetEvidenceId: string;
  readonly relationshipType: string;
  readonly rationale: string;
}): EvidenceRelationship {
  return {
    id: params.id,
    sourceEvidenceId: params.sourceEvidenceId,
    targetEvidenceId: params.targetEvidenceId,
    relationshipType: params.relationshipType,
    rationale: params.rationale,
  };
}

/**
 * Compose an immutable EvidenceGovernance.
 */
export function composeEvidenceGovernance(params: {
  readonly id: string;
  readonly governanceLevel: EvidenceGovernanceLevel;
  readonly decidedBy: string;
  readonly decidedAt: string;
  readonly rationale: string;
}): EvidenceGovernance {
  return {
    id: params.id,
    governanceLevel: params.governanceLevel,
    decidedBy: params.decidedBy,
    decidedAt: params.decidedAt,
    rationale: params.rationale,
  };
}

/**
 * Compose an immutable EvidenceAuditMetadata.
 */
export function composeEvidenceAuditMetadata(params: {
  readonly id: string;
  readonly auditedBy: string;
  readonly auditedAt: string;
  readonly confidenceLevel: EvidenceConfidenceLevel;
  readonly traceType: EvidenceTraceType;
  readonly auditNotes: string;
}): EvidenceAuditMetadata {
  return {
    id: params.id,
    auditedBy: params.auditedBy,
    auditedAt: params.auditedAt,
    confidenceLevel: params.confidenceLevel,
    traceType: params.traceType,
    auditNotes: params.auditNotes,
  };
}

/**
 * Compose an immutable AssessmentEvidence.
 */
export function composeAssessmentEvidence(params: {
  readonly id: string;
  readonly title: string;
  readonly evidenceType: EvidenceType;
  readonly source: EvidenceSource;
  readonly confidenceLevel: EvidenceConfidenceLevel;
  readonly references: readonly EvidenceReference[];
  readonly relationships: readonly EvidenceRelationship[];
  readonly governance: EvidenceGovernance;
  readonly auditMetadata: EvidenceAuditMetadata;
  readonly conceptIds: readonly string[];
  readonly status: EvidenceStatus;
  readonly assessmentGovernance: AssessmentGovernanceLevel;
  readonly provenance: AssessmentEvidenceProvenance;
}): AssessmentEvidence {
  const traceId = _deterministicId('evidence', [params.id]);
  const trace = composeAssessmentEvidenceTrace({ traceId });

  return {
    id: params.id,
    title: params.title,
    evidenceType: params.evidenceType,
    source: params.source,
    confidenceLevel: params.confidenceLevel,
    references: [...params.references],
    relationships: [...params.relationships],
    governance: params.governance,
    auditMetadata: params.auditMetadata,
    conceptIds: [...params.conceptIds],
    status: params.status,
    assessmentGovernance: params.assessmentGovernance,
    provenance: params.provenance,
    trace,
  };
}

/**
 * Compose immutable EvidenceRegistryMetadata.
 */
export function _composeEvidenceRegistryMetadata(
  nodes: readonly AssessmentEvidence[],
): EvidenceRegistryMetadata {
  const sortedIds = [...nodes].map((n) => n.id).sort();
  const registryId = _deterministicId('evidence-registry', sortedIds);

  return {
    registryId,
    version: '1.0.0',
    nodeCount: nodes.length,
    generatedFrom: 'deterministic_evidence_kernel',
    deterministic: true,
    randomUsed: false,
    timeDependency: false,
  };
}

/**
 * Compose an immutable EvidenceRegistry from pre-composed nodes.
 */
export function composeEvidenceRegistry(
  nodes: readonly AssessmentEvidence[],
): EvidenceRegistry {
  const sortedNodes = [...nodes].sort((a, b) => a.id.localeCompare(b.id));
  const metadata = _composeEvidenceRegistryMetadata(sortedNodes);

  return {
    metadata,
    nodes: sortedNodes,
  };
}

/**
 * Compose an immutable EvidenceRegistry from input.
 */
export function composeEvidenceRegistryFromInput(
  input: EvidenceInput,
): EvidenceRegistry {
  return composeEvidenceRegistry(input.nodes);
}

/**
 * Compose assessment evidence into a registry.
 */
export function composeAssessmentEvidenceCollection(params: {
  readonly evidence: readonly AssessmentEvidence[];
}): EvidenceRegistry {
  return composeEvidenceRegistry(params.evidence);
}

/**
 * Compose an assessment artifact enriched with evidence.
 */
export function composeAssessmentArtifactWithEvidence(params: {
  readonly artifactId: string;
  readonly artifactTitle: string;
  readonly evidence: readonly AssessmentEvidence[];
}): AssessmentArtifactWithEvidence {
  return {
    artifactId: params.artifactId,
    artifactTitle: params.artifactTitle,
    evidence: [...params.evidence],
  };
}
